[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qr9r4232uz0cxqq047asvze54zed59kqk3nkuazzz3lvpd982352xlfgn59"]

[[validator_account]]
address = "tnam1q9e04466jydfv6zj8dgkzflf7ynrv7f8wqpqgufc"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.122.105:26656"

[validator_account.consensus_key]
pk = "tpknam1qzh3kqmt28pv9395g5d4yj5qgj7dsep8n9yul72pf2c55ncumz8l26c3gg4"
authorization = "signam1qqqkq6tk9df6rnq3jhgzat2utnnvhjmu2vqy97jkwq5raejy5cysy70yha7ugavpvrq00dfwelrf4fu6kn3k4w0axn2r9g5xsmzwr0s0yy7rgq"

[validator_account.protocol_key]
pk = "tpknam1qrje9wln43erpwn5us9h9xulg9v8vgprmkdynpqau7u8w3wpw9vyzlv2cgz"
authorization = "signam1qz2shyy7nftgd4j9t0gcsj2afrn5dlv4l6akzrx6cg30qgmkypmdurwxt3zfkxw60kwxdn7p8xnsexfkkjcmtc55wx8r95wd9jhla2sd533ndv"

[validator_account.tendermint_node_key]
pk = "tpknam1qppf8c45jv50jz4vq9u5srx83elddazftjzq4lznh4vj87uthn4tsa0r3rr"
authorization = "signam1qparxqd88ya3yh72ms8h7rwr22ww5h47q8yg9l889nethnkm5y2gs4hyc2jdyzlprt37yxrydczaf4u3fx3ttjw3yum4d6j2dpfd7kg9avc0s0"

[validator_account.eth_hot_key]
pk = "tpknam1qypcgztfzsvylfvmevtyk4mveunvgfu7zlsgz56nyxc2wh5l9gchd2gpdfda4"
authorization = "signam1q8e2v78ta82dujzuh8qz3nw92eaqcka4zt6kqy33jh8tnkxtdv2tuwvpwyr26urpgktzkxa03pau96r3ck9sx59nvfm72x8kza6j7fk2qq4has56"

[validator_account.eth_cold_key]
pk = "tpknam1qypj8s85r2vfv4mqpaywf2kdhm79syusc4z8zgq3f6fuq9hu38gzqwc9v7qdf"
authorization = "signam1q85u06cvcxmlv8ryvz9etku0k3su2q4dnuajyuvlxe2su0vj7xyvywz6x6qv8gsnj8748zu0annrf3whppsedr5qpgcvsj4pd26hfpmwqq4dd7wk"

[validator_account.metadata]
email = "zeeem88@gmail.com"
discord = "seasting"
telegram = "zemji"
twitter = "@SeastingVD"
elements = ""

[validator_account.signatures]
tpknam1qr9r4232uz0cxqq047asvze54zed59kqk3nkuazzz3lvpd982352xlfgn59 = "signam1qr05kxtxwescp3a36chzz6zru6d9ce59rxcc07p3vt0snfn20pvfy7r08wxwchjnnea084kn7lszwjxsnh98qzgkxrhj7ct52r2uekgrppyn8h"

[[bond]]
source = "tnam1q9e04466jydfv6zj8dgkzflf7ynrv7f8wqpqgufc"
validator = "tnam1q9e04466jydfv6zj8dgkzflf7ynrv7f8wqpqgufc"
amount = "1000000"

[bond.signatures]
tpknam1qr9r4232uz0cxqq047asvze54zed59kqk3nkuazzz3lvpd982352xlfgn59 = "signam1qrdea2eat8rdlrpncjy3xpx5nvf9d5jkaqj9pmnj0ytvye5vnq2cs54zgta62kftx2qrdxwgcxnd8de92aaz3zjsnej277wcnuvdt0g2pz47ev"
